Utilities/ApsimTextFile.cs
Part of a fix for issue #6 of ApsimX.
=> Add constants defined in the header to the data table.

Utilities/MathUtilities.cs, Utilities/ReflectionUtilities.cs
Resolves #7 
Removed some unused stats, renamed others to make them clearer and added a 'Name' property.
=> Refactor RegressionStats

Utilities/MathUtilities.cs
Resolves #7 
Math fixes for some tests.
=> Fixes for some stat tests

APSIM.Shared.csproj, Utilities/ApsimTextFile.cs, Utilities/ExcelUtilities.cs, packages.config
=> ApsimX Log No16 Import Excel File as weather.met file

APSIM.Shared.csproj, packages.config
Working on Log 16 - using excel .xlsx files for weather data
=> Updates re Log 16 - using excel .xlsx files for weather data

Utilities/ApsimTextFile.cs
Working on Issue 16 - enabling use of excel files for weather data
=> Working on Issue 16 - enabling use of excel files for weather data

APSIM.Shared.csproj, Utilities/ApsimTextFile.cs
Working on Issue 16 - excel weather files
=> Working on Issue 16 - using excel files for weather data

Utilities/ApsimTextFile.cs
Working on Issue #16 Updated re Open method
=> Issue 16 update re Open Error on reports

Utilities/DateUtilities.cs
Working on Issue 837 - added date functions to handle dd-mmm date formats in Operations
=> Issue_837_Dates_in_Operations

Utilities/ApsimTextFile.cs
Was causing problems after map co-ordinates were obtained from an Excel weather file.
=> Check for null reference.

Utilities/XmlUtilities.cs
=> Try to get the right name for the serializer DLL.

APSIM.Shared.csproj, Properties/AssemblyInfo.cs
Almost forgot about this. See ApsimX #931.
=> Move to Net framework 4.5, and update copyright.

Utilities/XmlReaderCustom.cs
=> Remove unused variable, to avoid Mono compilation message

Utilities/XmlUtilities.cs
=> Allow Models serialization code to be used on non-Windows platforms.

Utilities/JobManager.cs
Needed for work on #1436 of ApsimX
=> Add a function to allow querying the number of completed jobs.

Utilities/SQLite.cs
=> Compare datatypes directly rather than via string comparison.

Utilities/SQLite.cs
=> Store enums in database as strings, not integers

Utilities/SQLite.cs
Should be able to handle enumerations a bit more safely.
=> Handle enumerations a little more robustly

Utilities/JobRunnerSync.cs
Applies this change to JobRunnerSync
=> Catch any exceptions raised during post-processing.

Utilities/StringUtilities.cs, Utilities/XmlUtilities.cs
Trying to make string comparison faster. See http://www.pvladov.com/2012/09/case-insensitive-string-comparison.html
=> Use a more efficient technique for case-insensitive string comparisons

Soils/Unit.cs, Utilities/ProcessUtilities.cs, Utilities/SQLite.cs
Test for NaN correctly
Make extern static functions private where possible
Simplify rethrow of exception
=> Minor changes to correct issues found by code analyis:

APSIM.Shared.csproj, Utilities/ExcelUtilities.cs, packages.config
Small change for reading Excel files.
=> Update NuGet packages.

Utilities/PathUtilities.cs, Utilities/SQLite.cs
This is intended to address ApsimX issue 2371
=> Don't try to use the %root% macro when creating relative paths

Utilities/XmlUtilities.cs
Allows streams to be used, as well as files.
=> Added ability to deserialize from streams

APSIM.Shared.csproj, packages.config
This package appears to be no longer required.
=> Removed reference to unused SharpZipLib package.

APSIM.Shared.csproj, Utilities/Firebird.cs, Utilities/IDatabaseConnection.cs, Utilities/SQLite.cs, packages.config
Add Firebird support for Datastore improvement.
SQLite is now a IDatabaseConnection.
=> Firebird support.

APSIM.Shared.csproj
Add IDatabaseConnection
Add Firebird.cs
=> Upgrade to .net 4.6

packages.config
=> Firebird package

Utilities/XmlUtilities.cs
Resolves #56 
@hol353 I couldn't find a way to do this in code and no method that currently does it.  Let me know if this is not good.
=> Add method to test the type of a xmlnode

Utilities/StringUtilities.cs
Working on APSIMInitiative/ApsimX#3186
=> Added a null check to string utilities.

Utilities/SQLite.cs
Resolves APSIMInitiative/ApsimX#3309
=> Allow boolean values to be reported.

Utilities/ApsimTextFile.cs, Utilities/ExcelUtilities.cs
Resolves APSIMInitiative/ApsimX#3299
Have these excel weather files ever actually worked? This code hasn't been touched in some time, and I find it hard to believe that a small change could have caused the problems that I saw. I even checked out 717db87, and it didn't seem to be working then either. 
I'm really not confident that this change is the right thing to do...I'm now able to run simulations using .xlsx weather files without errors, but I have no idea if the results are reasonable. Would love to hear from someone who has worked on this code before.
=> Bugfixes for excel weather files

Utilities/ExpressionEvaluator.cs
Resolves APSIMInitiative/ApsimX#2965
Would like to write some unit tests for this expression parser, but I'm not so sure that they belong in the ApsimX unit tests. Is it worth setting up a some unit tests just for APSIM.Shared?
=> Added support for unary minus to the expression parser

APSIM.Shared.csproj, packages.config
Working on APSIMInitiative/ApsimX#3374
=> Updated OpenXml nuget package.

Utilities/ReflectionUtilities.cs
Working on APSIMInitiative/ApsimX#3369
=> Allow users to set/use an array of dates in a manager script.

Utilities/ApsimTextFile.cs, Utilities/MathUtilities.cs
Working on APSIMInitiative/ApsimX#3488
=> Improved error messages when parsing text files.

Utilities/MathUtilities.cs
=> Speeding up SUM function

Utilities/MathUtilities.cs
Tests have examples for which integers are being summed by the reporting.  We need to add a function to sum ints.
=> Added method to sum integers

Utilities/JobRunnerAsync.cs, Utilities/SQLite.cs
=> Allow environment variable to constrain number of processors used.

Utilities/MathUtilities.cs
Resolves APSIMInitiative/ApsimX#3630
@sno036 Pretty sure I got it right. Let me know if this gives you any problems.
=> Added sample standard deviation to math utilities.

Utilities/Firebird.cs, Utilities/IDatabaseConnection.cs, Utilities/SQLite.cs
Needed for refactoring of code used to help resolve ApsimX issue 2821
=> Added "TableIsEmpty" function.

Utilities/ReflectionUtilities.cs
Working on APSIMInitiative/ApsimX#3788
=> Fixed autodocs bug on mac.

Utilities/ReflectionUtilities.cs
=> Removed unused variable.

Utilities/PathUtilities.cs
Resolves APSIMInitiative/ApsimX#3880
=> Path utils should be more accepting of null inputs.

Utilities/DataTableUtilities.cs
Working on APSIMInitiative/ApsimX#3923
=> Need to escape quote literals when generating a .csv file.

Utilities/MetUtilities.cs
=> Corrected handling of the case where a  "day" column is absent.

OldAPSIM/Shortcuts.cs
Resolves APSIMInitiative/ApsimX#3988
=> Fixed importing of shortcuts to shortcuts.

Utilities/ApsimTextFile.cs, Utilities/DataTableUtilities.cs, Utilities/ExpressionEvaluator.cs, Utilities/ReflectionUtilities.cs
Working on APSIMInitiative/ApsimX#4036
=> Use the invariant culture where possible.

Utilities/SQLite.cs
Working on APSIMInitiative/ApsimX#3995
=> Use text data type for string columns in sqlite
